version: "3"

services:
  db:
    image: mysql:5.7
    container_name: clean_arch_go_mysql
    command: mysqld -u root
    volumes:
      - ./example.sql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - clean_arch_go
  app:
    image: clean-arch
    build: ..
    container_name: clean_arch_app
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - clean_arch_go
networks:
  clean_arch_go:
